-- Seed data loaded on `supabase start` / `supabase db reset`.
--
-- Schema-level only. Application demo data (fixture agents, calls, and
-- evaluations for the demo location) is seeded by the API, which owns the
-- fixtures and the scoring pipeline:
--
--   pnpm --filter @copilot/api seed        (or `make seed`)
--
-- Supabase Auth is not used by this stack — the dashboard authenticates via
-- the HighLevel iframe session, so there is no seeded user.
select 1;
